# IMPORT

In [1]:
import numpy as np

## RANDOM-GENERATE X, A, Y

$K$ 는 dimension (우리의 경우에는 230), $N$은 데이터의 개수입니다. 

In [2]:
K = 3
N = 200

원래는 몰라야 하지만 우리는 정답을 먼저 정해놓고 다시 풀면서 이 방법이 잘 동작하는지 확인해볼 것이므로 정답 matrix를 먼저 만듭니다.

In [6]:
A = np.random.random((K, K)) * 2
print(A)

[[ 0.34260116  0.99840251  1.59308988]
 [ 1.42116001  0.85546586  1.37889195]
 [ 0.23864266  0.07815135  1.11745401]]


X matrix (question) 도 만듭니다.

In [10]:
X = np.random.random((N, K)) * 10
print(X[:5])

[[ 7.38493524  3.45453338  0.53734249]
 [ 7.52329812  0.40673706  7.50778058]
 [ 1.1642437   9.92801509  0.55176928]
 [ 4.19816993  6.29054674  0.52270094]
 [ 1.14201672  4.53215277  4.32912282]]


$Y = X \cdot A$ 모델에서 완벽한 피팅은 있을수 없습니다. epsilon은 에러입니다. 작은 값으로 놓습니다. 실제로는 매우 클지 모릅니다.

In [13]:
epsilon = np.random.random((N, K)) / 10
print(epsilon[:5])

[[ 0.02123502  0.00356955  0.0771902 ]
 [ 0.09699317  0.07113802  0.07690649]
 [ 0.04266116  0.03904781  0.02998237]
 [ 0.00285995  0.07867435  0.09518803]
 [ 0.00191619  0.06626679  0.08590634]]


In [20]:
Y = np.dot(X, A) + epsilon
print(Y[:5])

[[  7.58899989  10.37393686  17.20593958]
 [  5.04419901   8.51711065  21.01264254]
 [ 14.68250606   9.73763117  16.19096407]
 [ 10.50577      9.69233554  16.04132858]
 [  7.86720009   5.42188795  12.99218622]]


# LEAST SQUARES

$Y = XA$ 모델에서 세로로 한 줄씩 구합니다. 구한 w를 세로로 쌓고 나중에 transpose 합니다.

In [27]:
A_estimate = []

for k in range(K):
    y = Y[:, k]
    w = np.linalg.lstsq(X, y)[0]
    A_estimate.append(w)

In [29]:
A_estimate = np.array(A_estimate).T

실제 값 (`A`) 와 구한 값 (`A_estimate`)의 차이를 알아봅니다. 매우 잘 된 것을 알 수 있습니다.

In [30]:
print(A)

[[ 0.34260116  0.99840251  1.59308988]
 [ 1.42116001  0.85546586  1.37889195]
 [ 0.23864266  0.07815135  1.11745401]]


In [31]:
print(A_estimate)

[[ 0.3462932   1.00112763  1.59614879]
 [ 1.4225504   0.85931355  1.38359195]
 [ 0.24211021  0.08016376  1.11930968]]
